config/routes.rb
Rails.application.routes.draw do
  root to: 'words#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :words
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words = Word.all
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    @word.save
    redirect_to words_path
  end

  def edit
    @word = Word.find(params[:id])
  end

  def update
    @word = Word.find(params[:id])
    @word.update(word_params)
    redirect_to words_path
  end

  def destroy
    @word = Word.find(params[:id])
    @word.destroy
    redirect_to words_path
  end

  private

  def word_params
    params.require(:word).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SweetTweet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/words/edit.html.erb
<div class="container">
  <%= simple_form_for @word do |f| %>
    <%= f.input :name %>
    <%= f.submit "Save"%>
  <% end %>
</div>

app/views/words/index.html.erb
<h1>My keywords to follow</h1>

<ul>
  <% @words.each do |word| %>
    <li><%= word.name %>
        <%= link_to edit_word_path(word) do %>
          <i class="fas fa-pencil-alt"></i>
        <% end %>
        <%= link_to word_path(word), method: :delete, data: { confirm: "Sure?" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Add a keyword to follow", new_word_path %>

app/views/words/new.html.erb
<div class="container">
  <%= simple_form_for @word do |f| %>
    <%= f.input :name %>
    <%= f.submit "Add a keyword"%>
  <% end %>
</div>